# Generated by Django 3.0.3 on 2020-03-27 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_shown', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50, verbose_name='Название статьи')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/blog/', verbose_name='Картинка статьи')),
                ('text', models.TextField(blank=True, verbose_name='Текст статьи')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Категория')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_shown', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=50, verbose_name='Пользователь')),
                ('text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
            options={
                'verbose_name_plural': 'Commentaries',
            },
        ),
    ]
