# Generated by Django 3.0.3 on 2020-04-16 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_remove_commentary_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='category_articles', to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_commentaries', to='blog.Article'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commentaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
