# Generated by Django 3.0.3 on 2020-03-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200301_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Пользователь'),
        ),
    ]
