# Generated by Django 3.0.3 on 2020-02-20 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizAnswer',
            new_name='QuizOption',
        ),
        migrations.RemoveField(
            model_name='student',
            name='homework_responds',
        ),
        migrations.RemoveField(
            model_name='student',
            name='quiz_answers',
        ),
        migrations.AddField(
            model_name='homeworkrespond',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homeworkrespond',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Student'),
        ),
        migrations.AlterField(
            model_name='homeworkrespond',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
