# Generated by Django 3.0.3 on 2020-06-21 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20200618_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='HWRespondCommentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_shown', models.BooleanField(default=True)),
                ('text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commentaries_to_homework_respond', to=settings.AUTH_USER_MODEL)),
                ('homework_respond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_respond_commentaries', to='courses.HomeWorkRespond')),
            ],
            options={
                'verbose_name_plural': 'Commentaries',
            },
        ),
    ]
