# Generated by Django 3.0.3 on 2020-07-02 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_hwrespondcommentary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hwrespondcommentary',
            options={'verbose_name_plural': 'HWRespondCommentaries'},
        ),
        migrations.AddField(
            model_name='course',
            name='participation_requests',
            field=models.ManyToManyField(blank=True, related_name='participation_requests_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
