# Generated by Django 3.0.3 on 2020-02-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200222_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkrespond',
            name='file_attachment',
            field=models.FileField(blank=True, upload_to='files/courses/homeworks/'),
        ),
    ]
